[mainConfig]
appName = "GoAI"
host = "0.0.0.0"
port = 9090

[emailConfig]
authcode = "your email code"
email = "email"

[redisConfig]
host = "127.0.0.1"
port = 6379
password = ""
db = 0

[mysqlConfig]
host = "127.0.0.1"
port = 3306
user = "username"
password = "password"
databaseName = "dataname"
charset =  "utf8mb4"

[jwtConfig]
expire_duration= 8760
issuer= "L1nx32b"
subject= "GoAI"
key= "GOAI-V1"

[rabbitmqConfig]
host= "127.0.0.1"
port= 5672
username= "username"
password= "password"
vhost= "/"

[ragModelConfig]
embeddingModel= "text-embedding-v4"
chatModelName="qwen-turbo"
docDir = "./docs"
baseUrl="https://dashscope.aliyuncs.com/compatible-mode/v1"
dimension=1024

[voiceServiceConfig]
voiceServiceApiKey = "baiduApiKey"
voiceServiceSecretKey ="baiduSecretKey"

[modelKeyConfig]
apikey = "APIkey"